name: Update files
on:
  push:
  workflow_dispatch:
jobs:

  update:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update files
        run: |
          python .github/workflows/update.py
